---
- name: deploy VM on netlab and install apache2
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: ../vars.yml

  vars:
      ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  tasks:
      - name: deploy vm from template
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter: "{{ vcenter_datacenter }}"
          cluster: "{{ vcenter_cluster }}"
          resource_pool: "{{ vcenter_resource_pool }}"
          folder: "{{ vcenter_destination_folder }}"
          datastore: "{{ vcenter_datastore }}" 
          name: "{{ vm_name }}"
          template: "{{ vm_template }}"
          state: "{{ vm_state }}"
          wait_for_ip_address: yes
        register: vm_info

      - name: deployment ip address
        debug:
          msg: "server adress: {{ vm_info.instance.ipv4 }}"
  
      - name: apache2
        delegate_to: "student@{{ vm_info.instance.ipv4 }}"
        become: true
        become_method: sudo
        apt:
            name: apache2
            state: present
        vars:
          ansible_become_pass: student
      
      - name: firewall changes
        delegate_to: "student@{{ vm_info.instance.ipv4 }}"
        become: true
        become_method: sudo
        ufw:
          rule: allow
          port: 
            - '80'
            - '443'
          proto: tcp
        vars:
          ansible_become_pass: student