---
- name: Deploy VM from template
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: ../vars.yml


  tasks:
      - name: Deploy VM from templ 
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter: "{{ vcenter_datacenter }}"
          cluster: "{{ vcenter_cluster }}"
          resource_pool: "{{ vcenter_resource_pool }}"
          folder: "{{ vcenter_destination_folder }}"
          datastore: "{{ vcenter_datastore }}" 
          name: "{{ vm_name }}"
          template: "{{ vm_template }}"
          state: "{{ vm_state }}"
          wait_for_ip_address: yes
        register: vm_info

      - name: deploy info
        debug:
          msg: "server ip: {{ vm_info.instance.ipv4 }}"

      - name: add host to known_hosts keys
        ansible.builtin.shell: ssh-keyscan "{{ vm_info.instance.ipv4 }}" >> ~/.ssh/known_hosts
        delegate_to: localhost
        run_once: true

      - name: apache2
        delegate_to: "student@{{ vm_info.instance.ipv4 }}"
        become: true
        become_method: sudo
        apt:
            name: apache2
            state: present
        vars:
          ansible_become_pass: student


